# Generated by Django 6.1.1 on 2026-10-04 10:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('provider_id', models.CharField(max_length=20, unique=True)),
                ('placement', models.FloatField(default=0.0)),
                ('retention', models.FloatField(default=0.0)),
                ('fraud_status', models.CharField(choices=[('clean', 'Clean'), ('suspicious', 'Suspicious'), ('red_flag', 'Red Flag')], default='clean', max_length=20)),
                ('confidence', models.FloatField(default=0.0)),
                ('trainees_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Trainee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('master_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=15)),
                ('district', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('company_name', models.CharField(blank=True, max_length=200)),
                ('salary', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('salary_slip', models.FileField(blank=True, null=True, upload_to='salary_slips/')),
                ('shop_photo', models.FileField(blank=True, null=True, upload_to='shop_photos/')),
                ('confidence_score', models.IntegerField(default=20)),
                ('score_level', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='LOW', max_length=10)),
                ('bank_verified', models.BooleanField(default=False)),
                ('udyam_verified', models.BooleanField(default=False)),
                ('employer_otp_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.provider')),
            ],
        ),
        migrations.CreateModel(
            name='ConsentLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_id', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Revoked', 'Revoked')], default='Active', max_length=10)),
                ('granted_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('duration_months', models.IntegerField(default=12)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consents', to='core.trainee')),
            ],
        ),
        migrations.CreateModel(
            name='VerificationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('self_declaration', 'Self Declaration'), ('salary_slip', 'Salary Slip Upload'), ('bank', 'Bank Verification'), ('udyam', 'Udyam Verification'), ('employer_otp', 'Employer OTP Verification')], max_length=30)),
                ('points', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('trainee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verification_events', to='core.trainee')),
            ],
        ),
    ]
